-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:20 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tiposUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tiposUsuario` (
  `idtiposUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomberTipoUsuario` VARCHAR(45) NOT NULL,
  `descripcionTipoUsuario` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`idtiposUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuarios` INT NOT NULL,
  `nombre_usuarios` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `deleted` TINYINT NULL,
  `tiposUsuario_idtiposUsuario` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  INDEX `fk_usuarios_tiposUsuario_idx` (`tiposUsuario_idtiposUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tiposUsuario`
    FOREIGN KEY (`tiposUsuario_idtiposUsuario`)
    REFERENCES `mydb`.`tiposUsuario` (`idtiposUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id_comentarios` INT NOT NULL,
  `idComentario` VARCHAR(45) NOT NULL,
  `contenidoComentario` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` VARCHAR(45) NULL,
  `created_by` DATETIME NULL,
  `deleted` TINYINT(1) NULL,
  INDEX `fk_table1_usuarios1_idx` (`id_comentarios` ASC) VISIBLE,
  PRIMARY KEY (`idComentario`),
  CONSTRAINT `fk_table1_usuarios1`
    FOREIGN KEY (`id_comentarios`)
    REFERENCES `mydb`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensajes` (
  `idMensaje` INT NOT NULL,
  `id_mensajes` INT NOT NULL,
  `contenido` TEXT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, --CURRENT_TIMESTAMP: hora y fecha actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, --Borrado lógico - No se borra el registro fisicamente
  INDEX `fk_table1_usuarios2_idx` (`id_mensajes` ASC) VISIBLE,
  PRIMARY KEY (`idMensaje`),
  CONSTRAINT `fk_table1_usuarios2`
    FOREIGN KEY (`id_mensajes`)
    REFERENCES `mydb`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
